// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseFolder():Promise<string>;

export function GetCachedItems(arg1:Array<string>):Promise<Array<main.LauncherItem>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetIcon(arg1:string):Promise<string>;

export function GetIcons(arg1:Array<string>):Promise<Record<string, string>>;

export function GetTypeIcon(arg1:string):Promise<string>;

export function GetTypeIcons(arg1:Array<string>):Promise<Record<string, string>>;

export function HideWindow():Promise<void>;

export function OpenItem(arg1:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;

export function ScanFolder(arg1:string):Promise<Array<main.LauncherItem>>;

export function ScanFolders(arg1:Array<string>):Promise<Array<main.LauncherItem>>;

export function SetFolder(arg1:string):Promise<main.AppConfig>;

export function SetFolders(arg1:Array<string>):Promise<main.AppConfig>;

export function SetSettings(arg1:Array<string>,arg2:string):Promise<main.AppConfig>;

export function ShowWindow():Promise<void>;
