// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function GetCachedItems(arg1) {
  return window['go']['main']['App']['GetCachedItems'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetIcon(arg1) {
  return window['go']['main']['App']['GetIcon'](arg1);
}

export function GetIcons(arg1) {
  return window['go']['main']['App']['GetIcons'](arg1);
}

export function GetTypeIcon(arg1) {
  return window['go']['main']['App']['GetTypeIcon'](arg1);
}

export function GetTypeIcons(arg1) {
  return window['go']['main']['App']['GetTypeIcons'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenItem(arg1) {
  return window['go']['main']['App']['OpenItem'](arg1);
}

export function OpenItemLocation(arg1) {
  return window['go']['main']['App']['OpenItemLocation'](arg1);
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function ScanFolders(arg1) {
  return window['go']['main']['App']['ScanFolders'](arg1);
}

export function SetFolder(arg1) {
  return window['go']['main']['App']['SetFolder'](arg1);
}

export function SetFolders(arg1) {
  return window['go']['main']['App']['SetFolders'](arg1);
}

export function SetSettings(arg1, arg2) {
  return window['go']['main']['App']['SetSettings'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
